{% set name = "theme-material-darcula" %}
{% set version = "1.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/theme-material-darcula-{{ version }}.tar.gz
  sha256: ab5e6ad356d5134b9dc4d3775e875a4aa1747aa29f4a3d0ddb3859d471ed036d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - jupyter_packaging >=0.7.9
    - jupyterlab >=3.0.0
    - nodejs
    - pip
    - setuptools >=40.8.0
  run:
    - python >={{ python_min }}
    - jupyterlab >=3.0.0

test:
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/adhadse/theme-material-darcula
  summary: A Jupyterlab theme inspired by JetBrains IDE's Darcula scheme and Material Design.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - adhadse
